payload:
  # Homebrew
  - DOMAIN-SUFFIX,brew.sh
  - DOMAIN-SUFFIX,ghcr.io
  - DOMAIN-SUFFIX,greasyfork.org
  
  #################### HomeAssistant
  - DOMAIN-SUFFIX,basemaps.cartocdn.com # åœ°å›¾çš„CDNï¼Œä¸ä»£ç†åŠ è½½ç¼“æ…¢ï¼Œå…¶åŸå§‹æœåŠ¡å·²è¢«GFWåŒ…å«
  - DOMAIN-SUFFIX,home-assistant.io # ç¤¾åŒºï¼Œè®ºå›ç­‰ï¼Œä¸ä»£ç†åŠ è½½ç¼“æ…¢

    #################### openWRT
  - DOMAIN-SUFFIX,git.openwrt.org # openwrtæºç åº“
  - DOMAIN-SUFFIX,sources.cdn.openwrt.org # openwrtæºç åº“
  - DOMAIN-SUFFIX,mirror2.openwrt.org # openwrtæºç åº“
  - DOMAIN-SUFFIX,qichiyu.com
  - DOMAIN-SUFFIX,bulianglin.com

  #################### è®ºå›
  - DOMAIN-SUFFIX,v2rayssr.com # V2RaySSRç»¼åˆç½‘ï¼Œç¦æ­¢å¤§é™†IPè®¿é—®ï¼Œå†…æœ‰ä¸€äº›æ•™ç¨‹äº¤æµè´´
  
  #################### Game
  - DOMAIN-SUFFIX,thunderstore.io # modä¸‹è½½ç«™ï¼Œsteamæ¸¸æˆmodä¸‹è½½ç«™
  - DOMAIN-SUFFIX,pegasus-frontend.org # å¤©é©¬Gä¸»é¡µ
  - DOMAIN-SUFFIX,prodkeys.net # NSå¯†é’¥ä¸‹è½½
  - DOMAIN-SUFFIX,v3.stardew.info # æ˜Ÿéœ²è°·ç‰©è¯­åœ¨çº¿ç¼–è¾‘å™¨
  - DOMAIN-SUFFIX,simcitybuildit.com # æ¨¡æ‹ŸåŸå¸‚å¤©é™…çº¿-ipadç‰ˆï¼Œå¯ä»¥ç›´è¿ä½†æ˜¯å¡é¡¿ï¼Œä»£ç†æé«˜è®¿é—®ä½“éªŒ

    #################### ğŸ’»CodeSourceï¼Œç¨‹åºæºç è§„åˆ™é›†ï¼Œä¸€èˆ¬ç”¨äºç¼–è¯‘æˆ–ä¸‹è½½ç¨‹åºèµ„æº/æ›´æ–°ç­‰
  - DOMAIN-SUFFIX,artifacts.bitwarden.com # bitwardenå®‰è£…ç¨‹åºèµ„æºä¸‹è½½ç½‘å€ï¼Œä¸ä»£ç†çš„è¯bitwardenå®‰è£…è¿‡ç¨‹è¦10+åˆ†é’Ÿ
  - DOMAIN-SUFFIX,sub.xeton.dev # clashè®¢é˜…è½¬æ¢åœ°å€
  - DOMAIN-SUFFIX,www.python.org # Pythonæºç ç›¸å…³åˆ†å‘
  - DOMAIN-SUFFIX,cdn.kernel.org # Linuxå†…æ ¸ä¸‹è½½åœ°å€
  - DOMAIN-SUFFIX,sourceware.org # ä»£ç æ‰˜ç®¡æœåŠ¡å™¨ï¼ŒåŒ…æ‹¬å¤§éƒ¨åˆ†GNUå·¥å…·é“¾ï¼Œç¼–è¯‘openwrtä¼šç”¨åˆ°
  - DOMAIN-SUFFIX,ftpmirror.gnu.org # ä»£ç æ‰˜ç®¡æœåŠ¡å™¨ï¼ŒåŒ…æ‹¬å¤§éƒ¨åˆ†GNUå·¥å…·é“¾ï¼Œç¼–è¯‘openwrtä¼šç”¨åˆ°
  - DOMAIN-SUFFIX,mirror.lyrahosting.com # ä»£ç æ‰˜ç®¡æœåŠ¡å™¨ï¼ŒåŒ…æ‹¬å¤§éƒ¨åˆ†GNUå·¥å…·é“¾ï¼Œç¼–è¯‘openwrtä¼šç”¨åˆ°
  - DOMAIN-SUFFIX,ftp.nluug.nl # ä»£ç æ‰˜ç®¡æœåŠ¡å™¨ï¼ŒåŒ…æ‹¬å¤§éƒ¨åˆ†GNUå·¥å…·é“¾ï¼Œç¼–è¯‘openwrtä¼šç”¨åˆ°
  - DOMAIN-SUFFIX,ftp.wayne.edu # ä»£ç æ‰˜ç®¡æœåŠ¡å™¨ï¼ŒåŒ…æ‹¬å¤§éƒ¨åˆ†GNUå·¥å…·é“¾ï¼Œç¼–è¯‘openwrtä¼šç”¨åˆ°
  - DOMAIN-SUFFIX,mirror.cyberbits.eu # ä»£ç æ‰˜ç®¡æœåŠ¡å™¨ï¼ŒåŒ…æ‹¬å¤§éƒ¨åˆ†GNUå·¥å…·é“¾ï¼Œç¼–è¯‘openwrtä¼šç”¨åˆ°
  - DOMAIN-SUFFIX,static.rust-lang.org # ä»£ç æ‰˜ç®¡æœåŠ¡å™¨ï¼ŒåŒ…æ‹¬å¤§éƒ¨åˆ†GNUå·¥å…·é“¾ï¼Œç¼–è¯‘openwrtä¼šç”¨åˆ°
  - DOMAIN-SUFFIX,cache.ruby-lang.org # rubyä»£ç åˆ†å‘
  - DOMAIN-SUFFIX,git.codelinaro.org # codelinaroä»£ç åˆ†å‘
  - DOMAIN-SUFFIX,mirror.csclub.uwaterloo.ca # æ»‘é“å¢å¤§å­¦ä»£ç åˆ†å‘é•œåƒåŠ é€Ÿ
  - DOMAIN-SUFFIX,mirror.netcologne.de # å¾·å›½ç§‘éš†ç”µä¿¡å…¬å¸åˆ†å‘æœåŠ¡å™¨
  - DOMAIN-SUFFIX,www.busybox.net # busyboxæºç 
  - DOMAIN-SUFFIX,repo.jellyfin.org # Jellyfinä»“åº“ï¼Œäºšå¤ªåœ°åŒºçš„CDNï¼Œç”¨äºä¸‹è½½æ›´æ–°/æ’ä»¶ç­‰ç­‰
  - DOMAIN-SUFFIX,sgp1.mirror.jellyfin.org # Jellyfinä»“åº“ï¼Œäºšå¤ªåœ°åŒºçš„CDNï¼Œç”¨äºä¸‹è½½æ›´æ–°/æ’ä»¶ç­‰ç­‰
  - DOMAIN-SUFFIX,deb.debian.org # debianä»“åº“
  
  # IP Test & Check
  - DOMAIN-SUFFIX,vultr.com
  - DOMAIN-SUFFIX,test-ipv6.com
  - DOMAIN-SUFFIX,ipw.cn

  - DOMAIN-SUFFIX,fast.com
  - DOMAIN-SUFFIX,speedcheck.org
  - DOMAIN-SUFFIX,speedtest.net
  - DOMAIN-SUFFIX,dnscheck.tools
  - DOMAIN-SUFFIX,whoer.net
  - DOMAIN-SUFFIX,browserleaks.com
  - DOMAIN-SUFFIX,browserleaks.org
  - DOMAIN-SUFFIX,browserleaks.net

  - DOMAIN-SUFFIX,dnsleaktest.com
  - DOMAIN-SUFFIX,browserscan.net
  - DOMAIN-SUFFIX,surfshark.com
  - DOMAIN-SUFFIX,surfsharkdns.com
  - DOMAIN-SUFFIX,ip-api.com

  - DOMAIN-SUFFIX,ipleak.net
  - DOMAIN-SUFFIX,ip-score.com
  - DOMAIN-SUFFIX,888005.xyz
  - DOMAIN-SUFFIX,incolumitas.com

  - DOMAIN-SUFFIX,null-addr.com
  - DOMAIN-SUFFIX,null-addr.net
  - DOMAIN-SUFFIX,null-addr.org
  - DOMAIN-SUFFIX,null-addr.biz
  - DOMAIN-SUFFIX,null-addr.info
  - DOMAIN-SUFFIX,addr.tools

  - DOMAIN-SUFFIX,ifconfig.me
  - DOMAIN-SUFFIX,skk.moe
  - DOMAIN-SUFFIX,vultr.com
  - DOMAIN-SUFFIX,ping0.cc
  - DOMAIN-SUFFIX,incolumitas.com
